### ISSUE TITLE
PowerShell console does not open in VS Mac 17.4

### ISSUE THREAD

**Issue by mrward** [mrward/monodevelop-nuget-extensions#43]
Looks like the ConsoleInputEventArgs class has been made non-public.

```
ERROR [2022-07-27 15:15:56Z]: Could not create pad content
System.MethodAccessException: Attempt by method 'MonoDevelop.CSharpInteractive.CSharpInteractivePad.CreateConsoleView()' to access method 'System.EventHandler`1<System.__Canon>..ctor(System.Object, IntPtr)' failed.
   at MonoDevelop.CSharpInteractive.CSharpInteractivePad.CreateConsoleView()
   at MonoDevelop.CSharpInteractive.CSharpInteractivePad.Initialize(IPadWindow window)
   at MonoDevelop.Ide.Gui.PadContent.Init(IPadWindow window) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/PadContent.cs:line 76
   at MonoDevelop.Ide.Codons.PadCodon.InitializePadContent(IPadWindow window) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/PadCodon.cs:line 89
   at VisualStudioMac.UI.Pads.PadManager.CreatePadContent(Boolean force, PadCodon padCodon, PadWindow window, IDockItem item) in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/Pads/PadManager.cs:line 240
   at VisualStudioMac.UI.Pads.PadWindow.OnContentRequested() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/Pads/PadWindow.cs:line 277
   at VisualStudioMac.UI.Docking.DockItem.<get_Content>g__CreatePadContent|58_0() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/Docking/Cocoa/DockItem.cs:line 482
   at VisualStudioMac.UI.Docking.DockItem.get_Content() in /Users/runner/work/1/s/main/src/core/VisualStudio/UI/Docking/Cocoa/DockItem.cs:line 469
2022-07-27 15:15:56.085 VisualStudio[15806:263929] 
```

**Comment by mrward** [comment]
Fixed in ad3ab6ce79e61d835b3f810fda68fa2acb9151f0
